### ISSUE TITLE
problem initializing moment-recur

### ISSUE THREAD

**Issue by nha** [c-trimm/moment-recur#35]
Hello,

I have a problem initializing moment-recur.

TypeError: Object Wed Jan 01 2014 00:00:00 GMT+0100 has no method 'utcOffset'
    at Moment.moment.fn.dateOnly (.../node_modules/moment-recur/moment-recur.js:745:81)

Maybe this is just a version mismatch (I still have a .zone() method available) ?

Versions used (in my package.json) :
    "moment": "~2.5.1",
    "moment-recur": "^1.0.5"

Please let me know if I did something wrong.

Update : 
Running npm install --dev && gulp test gives the following output

```
$ gulp test
[12:23:53] Using gulpfile ...moment-recur/gulpfile.js
[12:23:53] Starting 'test'...
WARN [watcher]: Pattern "...moment-recur/bower_components/moment/moment.js" does not match any file.
WARN [watcher]: Pattern "...moment-recur/bower_components/moment-timezone/builds/moment-timezone-with-data.js" does not match any file.
INFO [karma]: Karma v0.12.35 server started at http://localhost:8080/
INFO [launcher]: Starting browser Chrome
WARN [web-server]: 404: /favicon.ico
INFO [Chromium 41.0.2272 (Ubuntu 0.0.0)]: Connected on socket MHC2liVo15IFgc3EzIJc with id 50993294
Chromium 41.0.2272 (Ubuntu 0.0.0) ERROR
  Uncaught Error: Can't find moment
  at ...node_modules/moment-recur/moment-recur.js:15


[12:24:08] 'test' errored after 14 s
[12:24:08] Error: 1
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:107:17)
    at Gulp.Orchestrator._emitTaskDone (...moment-recur/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at ...node_modules/moment-recur/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (...moment-recur/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (...node_modules/moment-recur/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at removeAllListeners (...moment-recur/node_modules/karma/lib/server.js:218:7)
    at Server.<anonymous> (...node_modules/moment-recur/node_modules/karma/lib/server.js:229:9)
    at Server.g (events.js:199:16)
```

**Comment by c-trimm** [comment]
Sorry for the long delay. Can you please provide the code you were using when you triggered this error?
